# Generated by Django 4.2.7 on 2023-11-15 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProducrtsModel",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
    ]
