# Generated by Django 4.2.7 on 2023-11-15 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cash_book", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProducrtsModel",
            new_name="ProductsModel",
        ),
    ]
