# Generated by Django 4.2.7 on 2023-11-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cash_book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashbookmodel",
            name="sale_date",
            field=models.DateTimeField(),
        ),
    ]
